# Generated by Django 3.1.1 on 2020-11-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='booking_instructions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='number_of_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='rate_of_costing',
            field=models.CharField(blank=True, choices=[('PER_DAY', 'Per Day'), ('ONE_TIME_PAYMENT', 'One Time Payment')], default='ONE_TIME_PAYMENT', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='requires_operator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='self_use',
            field=models.BooleanField(default=False),
        ),
    ]
