# Generated by Django 3.1.1 on 2020-11-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_new_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='new_user',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
