# Generated by Django 3.1.1 on 2020-11-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201019_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('item_name',), 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'ordering': ('name',), 'verbose_name': 'Item Category', 'verbose_name_plural': 'Item Categories'},
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
